version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cat appspec.yml
      - cd desktop/riderverse
      - npm install

  build:
    commands:
      - echo "Running build..."
      - npm run build

artifacts:
  base-directory: desktop/riderverse/dist  
  files:
    - '**/*'
