version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - echo "Installing dependencies..."
      - cd desktop/riderverse
      - npm install
  build:
    commands:
      - echo "Running build..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: build
